http://localhost:8080/api/health-check

###

GET http://localhost:8080/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDU0YTMzY2E5Zjk2ZmU0Y2I0NjI4ZjYiLCJ0b2tlbklkIjoiNmY3YTJlZWFiZmJhMzk4ZDZiZTYxYjRjZmFmZDc3MmYiLCJpYXQiOjE2MTYxNjA0MjYsImV4cCI6MTYxNjE2MTAyNn0.vBk08pE1f4cMrtVqXGIU9C8mUiEicPlpEQiaj1nJe6E

###

POST http://localhost:8080/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDY1YzAzYzNhZTM0NDUxZmMwMzEwMDQiLCJ0b2tlbklkIjoiMGZhZTU2NzcwM2YyNTFjZGRjNTg1NDQzOWRmOGQ3MzgiLCJpYXQiOjE2MTc1MDg2NjksImV4cCI6MTYxNzUwOTI2OX0.o7LS7yboE6-ciEKlV7gf4dElz9mE7Xrcj0ViaFSL1Fk

{
  "email": "henry2@classroom-interchat.ml",
  "password": "password",
  "name": "Henry",
  "isAdmin": false
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "admin@classroom-interchat.ml",
  "password": "password"
}

###

POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "dedrfrgtbhyjg5",
  "password": "password",
  "email": "abcd@def.com"
}

###

GET http://localhost:8080/api/auth/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDUyZDJmYzBiNWZjMTQxMDQzMDFkZjAiLCJ0b2tlbklkIjoiNjhmNjI2MTgwZTNkYjgwNGQwZmVjZGFiNmVlM2Y3ZDMiLCJpYXQiOjE2MTYwNDI1NzB9.hGEiuGwLwnt9UZCSxnobkQdJKbiolg_Ba_tpIw2mtGA

###

DELETE http://localhost:8080/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDUyZDJmYzBiNWZjMTQxMDQzMDFkZjAiLCJ0b2tlbklkIjoiNjhmNjI2MTgwZTNkYjgwNGQwZmVjZGFiNmVlM2Y3ZDMiLCJpYXQiOjE2MTYwNDI1NzB9.hGEiuGwLwnt9UZCSxnobkQdJKbiolg_Ba_tpIw2mtGA

###

GET http://localhost:8080/api/auth/random-number
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDU0YTMzY2E5Zjk2ZmU0Y2I0NjI4ZjYiLCJ0b2tlbklkIjoiNmY3YTJlZWFiZmJhMzk4ZDZiZTYxYjRjZmFmZDc3MmYiLCJpYXQiOjE2MTYxNjA0MjYsImV4cCI6MTYxNjE2MTAyNn0.vBk08pE1f4cMrtVqXGIU9C8mUiEicPlpEQiaj1nJe6E

###

GET http://localhost:8080/api/getUsername
