http://localhost:8080/api/health-check

###

GET http://localhost:8080/api/users

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "Admin",
  "mobileNumber": "12345678",
  "password": "password"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "react",
  "password": "express"
}

###

GET http://localhost:8080/api/auth/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlYWN0IiwidG9rZW5JZCI6IjA0MTE0OTU3NGZiYWY1ZDJiY2Q2Nzk1MjRkZDNkODUzIiwiaWF0IjoxNjE2MDM2MTI2fQ.mXi567H7Ja3Yt5TpGhHMYLWY5REDFwEFRBhBPwX81aI

###

DELETE http://localhost:8080/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlYWN0IiwidG9rZW5JZCI6IjA0MTE0OTU3NGZiYWY1ZDJiY2Q2Nzk1MjRkZDNkODUzIiwiaWF0IjoxNjE2MDM2MTI2fQ.mXi567H7Ja3Yt5TpGhHMYLWY5REDFwEFRBhBPwX81aI

###

GET http://localhost:8080/api/auth/random-number
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlYWN0IiwidG9rZW5JZCI6ImQzN2VmMmUyNGFmMGZhZTkxZDMwZmIzY2U3OTAxYWEwIiwiaWF0IjoxNjE2MDM2MTA5LCJleHAiOjE2MTYwMzYxMTl9.a_LMaC3sJnVcQw0p2dxh6aeXfezBl_SsZmqVCDvDDZw

###

GET http://localhost:8080/api/getUsername
