// =========================================================
// Database structures
// =========================================================

// Each type of objects lives in its own collection

Token object
{
  "id": "<token id>",
  "createdBy": "<REF user id>",
  "receivedBy": "<REF user id>",
  "createdAt": "<timestmap>",
  "classroom": "<REF classroom id>",
  "isValid": boolean,
  "value": "<string>"
}

User object
{
  "id": "<user id>",
  "name": "<string>",
  "email": "<email>",
  "password": "<hash>",
  "isAdmin": boolean,
  "createdAt": "<timestamp>",
  "authTokenIds": [ "<string>" ],  // IDs of refresh and access tokens. Refresh tokens are only valid if their IDs are in this array
  "emailVerification": "<string>" | null,  // the email verification code sent to user, null when email is already verified
  "lastVerifiedEmail": "<email>",
  "tokens": [ "<REF token id>" ]
}

Classroom object
{
  "id": "<classroom id>",
  "name": "<string>",
  "host": "<REF user id>",
  "createdAt": "<timestmap>",
  "closedAt": "<timestamp>", // null when the classroom is still open
  "participants": {
    "user": "<REF user id>",
    "permission": "instructor/student/requesting",
    "createdAt": "<timestamp>", // represents the time when the user first join the classroom
    "isOnline": boolean,
    "lastOnlineAt": "<timestamp>", // only meaningful when isOnline = false
    "isMuted": boolean
  },
  "messages": [ "<REF message id>" ],
  "isMuted": boolean
}

// This object is not stored to the database. It is sent
// by the server for previewing classroom before joining
PeekClassroom response
{
  "id": "<classroom id>",
  "name": "<string>",
  "host": "<REF user id>",
  "createdAt": "<timestmap>",
  "participantCount": number,
  "isMuted": boolean
}

Message object
{
  "id": "<message id>",
  "createdAt": "<timestamp>",
  "classroom": "<REF classroom id>",
  "sender": "<REF user id>",
  "type": "text|mcq|saq|question|reply",
  "content": "<string>"  // text content
  | {  // saq content
    "prompt": "<string>",
  }
  | {  // mcq content
    "prompt": "<string>",
    "choices": [ "<string>" ],
    "correct": [ number ],     // index of correct answer inside "choices"
    "multiSelect": boolean
  }
  | { // question content
    "isResolved": boolean,
    "content": "<string>"
  }
  | { // reply content
    "replyTo": "<REF message id>", // replyTo should not be populated
    "content": "<string>"
  }
}

// This object is not saved to the database, but is what the client receives
// from server when a new quiz arrives
// This object is embedded into Message.content
QuizContent repsonse
{
  "type": "SAQ|MCQ",
  "prompt": "<string>",
  "choices": [ "<string>" ],   // only MCQ
  "multiSelect": boolean  // only MCQ
}

// This object is also not saved to the database, but is what the client receives
// from server when a quiz result is released
// This object is embedded into Message.content
QuizContentWithResult repsonse
{
  "type": "SAQ|MCQ",
  "prompt": "<string>",
  "choices": [ "<string>" ],   // only MCQ
  "correct": [ number ],  // only MCQ
  "multiSelect": boolean,
  "result": [
    {
      "user": "<user id>",
      "content": "<string>" | [ number ],
      "createdAt": "<timestamp>"
    }
  ]
}

QuizAnswer object
{
  "id": "<quizanswer id>",
  "quiz": "<REF message id>",
  "createdAt": "<timestamp>",
  "user": "<REF user id>",
  "content": "<string>" | [ number ]
}

############################################################

// =========================================================
// REST APIs
// =========================================================
// /auth

// Login = generate access and refresh token for this login session

POST /api/auth/login

{
  "email": "<email>",
  "password": "<string>"
}

RESPONSE:
{
  "accessToken": "<string>",
  "refreshToken": "<string>",
  "user": {
    "name": "<string>",
    "email": "<email>",
    "id": "<user id>",
    "isAdmin": boolean,
    "createdAt": "<timestamp>"
  }
}

############################################################

// Sign up
// This endpoint does not log in the user automatically.
// Send a separate login request to do so

POST /api/auth/signup

{
  "name": "<string>",
  "email": "<email>",
  "password": "<string>"
}

RESPONSE:
{
  "name": "<string>",
  "email": "<email>",
  "id": "<user id>",
  "createdAt": "<timestamp>",
  "isAdmin": boolean
}

############################################################

// Request a new access token using the refresh token when the old one expires
// Should be done automatically when any request fails with UNAUTHORIZED status

GET /api/auth/token
Authorization: Bearer <refresh token>

RESPONSE:
{
  "accessToken": "<string>",
  "userId": "<user id>"
}

############################################################

// Makes a refresh token invalid

DELETE /api/auth/logout
Authorization: Bearer <refresh token>

RESPONSE: NO_CONTENT

############################################################

// =========================================================
// /user

// Request user profile data
// Only allowed if :userId matches access token

GET /api/user/:userId
Authorization: Bearer <access token>



RESPONSE:
{
  "name": "<string>",
  "email": "<email>",
  "id": "<user id>",
  "isAdmin": boolean,
  "createdAt": "<timestamp>"
}

############################################################

// Admin route: create a new user with less restriction

POST /api/user
Authorization: Bearer <access token>

{
  "name": "<string>",
  "email": "<email>",
  "isAdmin": boolean,
  "emailVerification": "<string>" | null,
  "password": "<string>",
  "lastVerifiedEmail": "<email>"
}

RESPONSE:
{
  "name": "<string>",
  "email": "<email>",
  "password": "<hash>",
  "id": "<user id>",
  "isAdmin": boolean,
  "createdAt": "<timestamp>",
  "emailVerification": "<string>" | null,
  "lastVerifiedEmail": "<email>"
}

############################################################

// Update user profile data
// Only allowed if :userId matches access token or user is admin
// Can update name, email or password
// Only need to provide fields that are being updated
// Other fields can be omitted

PATCH /api/user/:userId
Authorization: Bearer <access token>

{
  "name": "<string>",
  "email": "<email>",
  "password": "<string>"
}

RESPONSE:
{
  "name": "<string>",
  "email": "<email>",
  "id": "<user id>",
  "createdAt": "<timestamp>",
  "isAdmin": boolean
}

############################################################

// =========================================================
// /token

// Get all tokens of a given user id
// "created" are tokens created by the user
// "received" are tokens received by the user
GET /api/token/:userId
Authorization: Bearer <access token>



RESPONSE:
{
  "created": [
    {
      "id": "<token id>",
      "createdBy": {
        "id": "<user id>",
        "name": "<string>",
        "email": "<email>"
      },
      "receivedBy": {
        "id": "<user id>",
        "name": "<string>",
        "email": "<email>"
      },
      "createdAt": "<timestamp>",
      "isValid": boolean
    }
  ],
  "received": [
    {
      "id": "<token id>",
      "createdBy": {
        "id": "<user id>",
        "name": "<string>",
        "email": "<email>"
      },
      "receivedBy": {
        "id": "<user id>",
        "name": "<string>",
        "email": "<email>"
      },
      "createdAt": "<timestamp>",
      "isValid": boolean
    }
  ]
}

############################################################

// Sets isValid of a token to false
// isValid is just for instructors' reference, not "useful" in our system

PATCH /api/token/:tokenId/invalidate
Authorization: Bearer <access token>



RESPONSE: NO_CONTENT

// create token is handled in socket.io

// =============================================
// /classroom

// handled in socket.io