# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, develop, testing-framework ]
  pull_request:
    branches: [ main, develop, testing-framework ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1.7.4
      
      - run: yarn run test:server

      - run: yarn run test:client
